// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Locations.Models;

public partial class Registration
{
    public string CarId { get; set; }

    public int? RegionId { get; set; }
}